index:
    path: /
    controller: App\Controller\DefaultController::index

mannequin_index:
    path: /mannequins
    controller: App\Controller\MannequinController::index

defile_index:
    path: /defiles
    controller: App\Controller\DefileController::index

marque_index:
    path: /marques
    controller: App\Controller\MarqueController::index
